spring:
  datasource:
    url: jdbc:postgresql://${roundhouse.proxy.rlwy.net}:${53454}/${railway}
    username: ${postgres}
    password: ${xXjkdpidvpaFbEXHQKeRMzblJvRBGkiU}
    name: railway
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
