spring:
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:32567/railway
    username: root
    password: WKgtSQcKCvJBExUhKzrvHlTcQjdBXgor
    name: ecommerceDB

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes